import { Globe, Smartphone, Server, Palette, Database, Sparkles } from "lucide-react";

export const SERVICES = [
  {
    id: "web-dev",
    icon: <Globe className="w-6 h-6" />,
    title: "Web Development",
    description: "Modern, responsive web applications built with cutting-edge frameworks. From landing pages to complex web platforms.",
    tags: ["React", "Next.js", "Vite", "Tailwind CSS", "TypeScript", "HTML/CSS"],
  },
  {
    id: "mobile-dev",
    icon: <Smartphone className="w-6 h-6" />,
    title: "Mobile App Development",
    description: "Cross-platform mobile apps that work seamlessly on iOS and Android with a single codebase.",
    tags: ["Flutter", "Dart", "REST APIs", "State Management", "Play Store / App Store"],
  },
  {
    id: "backend-dev",
    icon: <Server className="w-6 h-6" />,
    title: "Backend & API Development",
    description: "Scalable, secure server-side systems and RESTful APIs that power your applications reliably.",
    tags: ["Django", "Python", "Node.js", "Hono", "REST API", "JWT Auth"],
  },
  {
    id: "ui-ux",
    icon: <Palette className="w-6 h-6" />,
    title: "UI/UX Design",
    description: "Clean, intuitive interfaces designed for conversion and engagement — from wireframes to polished prototypes.",
    tags: ["Figma", "Responsive Design", "Accessibility", "Design Systems", "User Research"],
  },
  {
    id: "db-cloud",
    icon: <Database className="w-6 h-6" />,
    title: "Database & Cloud",
    description: "Efficient database design and cloud deployment for performance, reliability, and scalability.",
    tags: ["PostgreSQL", "MySQL", "Firebase", "Vercel", "Cloud Hosting", "Data Modeling"],
  },
  {
    id: "ai-auto",
    icon: <Sparkles className="w-6 h-6" />,
    title: "AI & Automation",
    description: "Intelligent solutions that automate workflows and add smart capabilities to your business systems.",
    tags: ["Python ML", "OpenCV", "Face Recognition", "Data Analysis", "Process Automation"],
  },
];

export const PROJECTS = [
  /* ── Live client projects (shown first) ── */
  {
    category: "AgriTech",
    title: "Farm with Irene",
    desc: "Professional agricultural consultation and sustainable farming solutions platform connecting farmers with certified agronomists for crop advisory, soil analysis, and market guidance.",
    tags: ["React", "Next.js", "Tailwind CSS", "Agriculture"],
    desktopImage: "/assets/Assets/portfolio/Farmwithirene.png",
    mobileImage: "/assets/Assets/portfolio/mobilevuewfarmwithiren.png",
    links: [{ type: "live", href: "https://www.farmwithirene.online/" }],
  },
  {
    category: "Property Tech",
    title: "GetQeja",
    desc: "Smart property rental platform helping Kenyans find verified houses, apartments and commercial spaces across all 47 counties  with personalized matches, verified listings, and viewing support.",
    tags: ["React", "Next.js", "PostgreSQL", "Node.js"],
    desktopImage: "/assets/Assets/portfolio/getkejadesktop.png",
    mobileImage: "/assets/Assets/portfolio/getkejamobile.png",
    links: [{ type: "live", href: "https://www.getkeja.online/" }],
  },
  {
    category: "Infrastructure",
    title: "Hiracore",
    desc: "End-to-end water and energy infrastructure company delivering solar installations, borehole drilling, water treatment, irrigation systems, and engineering consultancy across Kenya.",
    tags: ["React", "Next.js", "Tailwind CSS", "B2B"],
    desktopImage: "/assets/Assets/portfolio/hidracore.png",
    mobileImage: "/assets/Assets/portfolio/hidracoremobile.png",
    links: [{ type: "live", href: "https://hidracore.netlify.app/" }],
  },
  {
    category: "Media & News",
    title: "Taarifa",
    desc: "Modern digital news platform delivering real-time breaking news, business intelligence, politics, sports, and entertainment content — built for speed, SEO, and high-traffic readership.",
    tags: ["React", "Next.js", "REST API", "CMS"],
    desktopImage: "/assets/Assets/portfolio/taarifadesktop.png",
    mobileImage: "/assets/Assets/portfolio/taarifamobile.png",
    links: [{ type: "live", href: "https://taarifa.netlify.app/" }],
  },
  // /* ── Open-source / GitHub projects ── */
  // {
  //   category: "Property Tech",
  //   title: "RENT_ME_A_KEJA",
  //   desc: "Full-stack property rental platform enabling landlords to list properties and tenants to search, book, and manage rentals.",
  //   tags: ["React", "Vite", "Django", "REST API", "PostgreSQL"],
  //   links: [{ type: "code", href: "https://github.com/simon9001/rent-me-a-keja" }],
  // },
  // {
  //   category: "Management System",
  //   title: "Car Rental Management System",
  //   desc: "Web-based system for managing vehicle listings, bookings, customers, and availability with a clean admin dashboard.",
  //   tags: ["Django", "Python", "Bootstrap", "PostgreSQL"],
  //   links: [{ type: "code", href: "https://github.com/simon9001/car-rental-system" }],
  // },
  // {
  //   category: "Civic Tech",
  //   title: "Online Voting System",
  //   desc: "Secure online voting platform with user authentication, vote integrity checks, and real-time result tallying.",
  //   tags: ["Django", "React", "JWT", "System Security"],
  //   links: [{ type: "code", href: "https://github.com/simon9001/online-voting-system" }],
  // },
  // {
  //   category: "AI / Computer Vision",
  //   title: "Face Recognition Attendance",
  //   desc: "AI-powered attendance system using face recognition to automatically log attendance for institutions.",
  //   tags: ["Python", "OpenCV", "Machine Learning", "Computer Vision"],
  //   links: [{ type: "code", href: "https://github.com/simon9001/face-recognition-attendance" }],
  // },
];

export const PRICING = [
  {
    plan: "Starter",
    price: "From KES 15000",
    desc: "Perfect for landing pages and simple business sites.",
    features: [
      "Responsive Design",
      "Up to 5 Pages",
      "Contact Form",
      "Basic SEO Setup",
      "1 Month Support",
    ],
    recommended: false,
  },
  {
    plan: "Professional",
    price: "From KES 30000",
    desc: "Ideal for growing businesses and E-commerce sites.",
    features: [
      "Custom Web Application",
      "CMS Integration",
      "E-commerce Ready",
      "Advanced SEO",
      "3 Months Support",
    ],
    recommended: true,
  },
  {
    plan: "Enterprise",
    price: "Custom",
    desc: "For complex systems, mobile apps and AI solutions.",
    features: [
      "Full System Architecture",
      "Mobile App (Flutter)",
      "AI/Automation Logic",
      "Priority Support",
      "Dedicated Team",
    ],
    recommended: false,
  },
];

// ============================================================
// BLOG POSTS — Add your blog entries here
// Each post needs: id, title, excerpt, category, date, author, readTime, tags, content
// The "content" field supports simple paragraphs as an array of strings.
// ============================================================
export const BLOG_POSTS = [
  {
    id: "how-much-does-a-website-cost-in-kenya-2025",
    title: "How Much Does It Cost to Build a Website in Kenya? (2025 Pricing Guide)",
    excerpt:
      "Wondering what a website costs in Kenya in 2025? We break down real pricing for every type of project — from simple landing pages to full e-commerce platforms — so you can budget with confidence.",
    category: "Web Development",
    date: "2025-06-10",
    author: "Simon Gatungo",
    readTime: "6 min read",
    tags: ["Website Cost Kenya", "Web Development Pricing", "Kenya 2025", "Small Business"],
    content: [
      "One of the most common questions we get from Kenyan entrepreneurs and business owners is: 'How much does a website cost?' The honest answer depends on what you need — but in this guide, we break down real-world pricing across every type of project so you can plan your budget with confidence.",
      "A simple landing page or single-page website — ideal for service businesses, freelancers, and startups testing a new idea — typically costs between KES 15,000 and KES 25,000. These include a clean design, contact form, mobile responsiveness, and basic SEO setup. They're fast to build (1–2 weeks) and perfect for getting online quickly.",
      "A full business website with 5–10 pages, a blog, a content management system (CMS), and advanced SEO typically runs between KES 30,000 and KES 80,000. At this level you get a professional online presence that you can update yourself without touching any code. Most SMEs and established Kenyan businesses fall into this category.",
      "E-commerce websites — where customers can browse products, add to cart, and pay (including M-Pesa integration) — cost between KES 60,000 and KES 200,000 depending on the number of products, payment gateways, and custom features. A well-built online shop can pay for itself within months if marketed correctly.",
      "Custom web applications — booking systems, SaaS platforms, management dashboards, or marketplace-style platforms — start from KES 100,000 and can go much higher depending on complexity. These are bespoke systems built around your specific business logic, usually with a backend API, database design, and admin panel.",
      "Beyond the build cost, budget for ongoing expenses: domain registration (roughly KES 1,000–2,000 per year), web hosting (KES 3,000–15,000 per year depending on traffic), and maintenance. Some agencies, including Jengeame, include the first 1–3 months of support in the project price.",
      "The cheapest option is rarely the best one. A poorly built website that loads slowly, isn't mobile-friendly, or breaks after six months will cost you far more in the long run — both in lost customers and in rebuilding costs. Focus on value: a professionally built site by a reputable Kenyan agency will generate leads, build trust, and work for your business 24 hours a day.",
    ],
  },
  {
    id: "10-signs-your-business-needs-a-new-website",
    title: "10 Signs Your Business Needs a New Website in 2025",
    excerpt:
      "Is your website secretly hurting your business? Here are 10 clear signs it's time for a redesign — and what to do about each one.",
    category: "Business & Strategy",
    date: "2025-06-01",
    author: "Antony Ochieng",
    readTime: "5 min read",
    tags: ["Website Redesign", "Business Tips", "Kenya", "Digital Presence"],
    content: [
      "Your website is often the first impression a potential customer has of your business. If it's slow, outdated, or hard to navigate, you're losing sales before anyone even calls you. Here are 10 clear signs it's time to invest in a new website in 2025.",
      "1. It's not mobile-friendly. Over 80% of Kenyan internet users browse on smartphones. If your site doesn't look great on a phone screen, you're invisible to the majority of your potential customers. Google also ranks mobile-friendly sites higher, so this is a double hit on your visibility.",
      "2. It loads slowly. A site that takes more than 3 seconds to load loses over half its visitors before they even see your content. Slow sites are usually built on outdated technology or cheap shared hosting. Modern frameworks like Next.js can cut load times dramatically.",
      "3. It looks like it was built ten years ago. Design trends evolve. A site with dated fonts, cluttered layouts, or stock photos that look fake signals low professionalism. Customers judge your brand quality by your website quality — fair or not.",
      "4. You can't update it yourself. If you have to call your developer every time you need to change a phone number or add a new service, you need a CMS-powered site. Modern websites give business owners full control over their own content.",
      "5. It doesn't rank on Google. If you search your business name or main service and your website doesn't appear on the first page, you have a technical SEO problem. This could be slow performance, missing metadata, poor site structure — all things a rebuild fixes at the root.",
      "6. It has no SSL certificate. If your site shows 'Not Secure' in the browser address bar, customers don't trust it with their information. HTTPS is a baseline requirement in 2025 — both for security and for Google ranking.",
      "7. Your bounce rate is very high. If visitors land on your site and leave immediately, the design, copy, or user experience is failing them. A bounce rate above 80% is a red flag that your site isn't meeting visitor expectations.",
      "8. It doesn't connect to your business tools. If your website can't link to your booking system, payment processor, WhatsApp, or CRM, it's costing you time and missed leads every single day.",
      "9. Your competitors have better sites. In business, perception is reality. If your competitors have sharper, faster, more professional websites, you're losing the comparison before any conversation even starts.",
      "10. It generates zero leads. A website that has no clear call-to-action, no contact forms, or no way to capture enquiries is an online brochure — not a business tool. If your site isn't generating calls or messages, it's time to rethink the whole thing.",
    ],
  },
  {
    id: "how-to-start-online-business-kenya-2025",
    title: "How to Start an Online Business in Kenya in 2025: The Complete Tech Guide",
    excerpt:
      "Ready to take your business online in Kenya? From domain name to M-Pesa payments, this step-by-step guide covers everything you need to launch and grow successfully in 2025.",
    category: "Business & Strategy",
    date: "2025-05-20",
    author: "Simon Gatungo",
    readTime: "8 min read",
    tags: ["Online Business Kenya", "E-commerce Kenya", "Start Business Kenya", "M-Pesa"],
    content: [
      "Kenya's digital economy is booming. With over 22 million internet users, a thriving mobile money ecosystem, and a young tech-savvy population, there has never been a better time to start an online business in Kenya. Whether you're launching a shop, a services business, or a digital product, here is the complete step-by-step tech guide for 2025.",
      "Step 1: Register your business and secure your domain name. Before anything else, register your business with Kenya's Business Registration Service (BRS). Then grab your domain — ideally a .co.ke (around KES 1,500/year) for local credibility, or a .com for global reach. Secure your brand name before someone else does.",
      "Step 2: Build a professional website. Your website is your 24/7 sales team. For a business site or blog, Next.js or WordPress are excellent choices. For e-commerce, a custom-built platform tailored to Kenyan payment methods will serve you far better than a generic template. Prioritize mobile-first design — the majority of your Kenyan customers are on phones.",
      "Step 3: Integrate M-Pesa payments. M-Pesa is the dominant payment method in Kenya, and any serious online business needs to accept it. Safaricom's Daraja API allows you to integrate Lipa Na M-Pesa (STK Push) directly into your website, so customers receive a payment prompt on their phone at checkout. This is non-negotiable for converting Kenyan customers.",
      "Step 4: Sort your logistics. If you're selling physical products, partner with delivery services like Sendy, Fargo Couriers, or G4S Kenya. Build a simple order management system or use WhatsApp Business to manage orders and deliveries until your volume justifies full automation.",
      "Step 5: Market your business online. A website alone won't bring customers — you need traffic. Start with Google My Business (free and puts you on Google Maps immediately), then build a presence on Instagram, TikTok, and Facebook, where Kenyan consumers are most active. Consider running Google Ads for instant visibility on searches like 'buy X in Nairobi.'",
      "Step 6: Track everything from day one. Install Google Analytics and Google Search Console immediately — both are free. These tools tell you where your visitors come from, what pages they read, what keywords bring them to you, and where you're losing people. Use this data to make smart decisions about where to invest your time and marketing budget.",
    ],
  },
  {
    id: "local-seo-kenya-rank-on-google-2025",
    title: "How to Rank on Google in Kenya: Local SEO Guide for Small Businesses (2025)",
    excerpt:
      "Not showing up when customers search for your services in Kenya? This practical local SEO guide shows you exactly what to do — step by step — to get found on Google in 2025.",
    category: "SEO & Marketing",
    date: "2025-05-12",
    author: "Simon Gatungo",
    readTime: "7 min read",
    tags: ["SEO Kenya", "Local SEO", "Google Ranking Kenya", "Nairobi Business"],
    content: [
      "If your business isn't appearing on Google when potential customers search for your services in Kenya, you are losing sales every single day. Local SEO — Search Engine Optimization for your geographic area — is one of the highest-return marketing investments a Kenyan small business can make. Here is a practical, step-by-step guide built specifically for the Kenyan market.",
      "Step 1: Claim and fully optimize your Google Business Profile. This is the single most impactful thing a Kenyan small business can do for local SEO — and it is completely free. Go to business.google.com, claim your listing, and fill in every field: business name, category, physical address, phone number, opening hours, website link, and high-quality photos. Businesses with complete Google profiles are 70% more likely to attract walk-in visits and calls.",
      "Step 2: Make your website fast and mobile-friendly. Google ranks mobile performance first in 2025. Your site's speed on a mobile phone directly determines where you appear in search results. Use Google's free PageSpeed Insights tool to check your score. A slow website will never rank well — regardless of how good your content is.",
      "Step 3: Target the right Kenyan keywords. Searches in Kenya often include specific location terms — 'in Nairobi', 'in Mombasa', 'in Westlands', or county names. Research what your customers actually type into Google. 'Plumber Westlands', 'web designer Nairobi', 'catering Karen' — these hyper-local keywords are less competitive and convert far better than broad generic terms.",
      "Step 4: Publish useful, locally relevant content. Write blog posts that answer real questions your Kenyan customers are asking. Articles like 'How much does X cost in Kenya?' or 'Best Y services in Nairobi' perform extremely well in local search. Google rewards websites that consistently publish helpful, original content over time.",
      "Step 5: Build local backlinks. Ask Kenyan business directories (Kenya Yellow Pages, Bizna Kenya, BrighterMonday for service businesses), industry associations, and local blogs to link to your website. Backlinks from relevant Kenyan websites are a strong ranking signal that tells Google your business is legitimate and trusted.",
      "Step 6: Collect reviews consistently. Online reviews on Google, Facebook, and industry platforms influence both customer decisions and search rankings. Make it a habit to ask every satisfied customer for a Google review — and respond professionally to every single one. Active, reviewed businesses rank higher and convert better. Local SEO takes 3–6 months to compound, but the results are lasting and highly cost-effective.",
    ],
  },
  {
    id: "mpesa-payment-integration-website-kenya",
    title: "How to Accept M-Pesa Payments on Your Website: A 2025 Developer's Guide",
    excerpt:
      "M-Pesa is how Kenya pays. This guide walks developers and business owners through integrating Safaricom's Daraja API into a website — from sandbox setup to going live.",
    category: "Backend",
    date: "2025-05-05",
    author: "Antony Ochieng",
    readTime: "8 min read",
    tags: ["M-Pesa Integration", "Daraja API", "Kenya Payments", "Backend", "E-commerce Kenya"],
    content: [
      "M-Pesa is the lifeblood of the Kenyan economy. With over 32 million active users and billions processed monthly, it is the payment method your Kenyan customers prefer above all others. If your website or app does not accept M-Pesa, you are turning away the majority of your potential buyers. Here is how to integrate it properly using Safaricom's Daraja API in 2025.",
      "What is the Daraja API? Daraja is Safaricom's official developer portal that gives you programmatic access to M-Pesa services. The most widely used feature for e-commerce is Lipa Na M-Pesa Online (also called STK Push) — this sends a real-time payment prompt directly to the customer's phone the moment they click 'Pay' on your website.",
      "Step 1: Register on the Safaricom Developer Portal. Visit developer.safaricom.co.ke and create a developer account. Once approved, create a new app and you will receive a Consumer Key and Consumer Secret — treat these like passwords. Start in the sandbox (test) environment before touching real money.",
      "Step 2: Generate your access token. Every Daraja API call requires a short-lived Bearer Token. You generate it by making a POST request to the OAuth endpoint with your credentials base64-encoded in the Authorization header. This token expires every hour, so your backend must refresh it automatically in the background.",
      "Step 3: Trigger the STK Push. To request payment from a customer, call the /mpesa/stkpush/v1/processrequest endpoint with the transaction amount, the customer's phone number (in 254XXXXXXXXX format), your business shortcode, and a callback URL. Within 5–10 seconds the customer sees a PIN prompt on their phone. They enter their M-Pesa PIN and the transaction completes.",
      "Step 4: Handle the payment callback reliably. After the customer pays or cancels, M-Pesa sends a POST request to your callback URL with the full transaction result. Your backend must handle this correctly — verify the transaction, update the order status, send a receipt to the customer, and log everything. Your callback URL must be publicly accessible HTTPS — no localhost. Use a service like ngrok during development for testing.",
      "Step 5: Test thoroughly and apply for go-live. Use Safaricom's sandbox with test credentials to simulate every scenario — successful payment, failed payment, timeout, customer cancellation. Once everything works perfectly, submit your app through the Daraja portal for Safaricom's go-live review. Common mistakes: wrong phone number format, callback URL not HTTPS, and not handling transaction timeouts. At Jengeame, M-Pesa integration is a standard deliverable in every e-commerce project we build for Kenyan clients.",
    ],
  },
  {
    id: "nextjs-vs-wordpress-2025",
    title: "Next.js vs WordPress in 2025: Which Is Better for Your Business Website?",
    excerpt:
      "WordPress powers over 40% of the web — but Next.js is rapidly taking over for serious business sites. Here's an honest comparison to help you choose the right platform in 2025.",
    category: "Web Development",
    date: "2025-04-28",
    author: "Simon Gatungo",
    readTime: "6 min read",
    tags: ["Next.js", "WordPress", "Web Development", "Business Website", "Kenya"],
    content: [
      "WordPress has dominated the web for over 20 years — and for good reason. It is powerful, flexible, and backed by a massive ecosystem. But Next.js, a React-based framework from Vercel, is rapidly becoming the preferred choice for serious business websites in 2025. Which one should you choose? Here is an honest comparison.",
      "WordPress is a content management system (CMS) at its core. It is beginner-friendly, has thousands of themes and plugins, and you can get a basic site running quickly. For businesses that publish lots of content and need non-technical editors to update the site independently, WordPress remains a solid choice.",
      "Next.js is a full-stack React framework that gives developers complete control over performance, architecture, and user experience. Pages are server-rendered or statically generated, which means they load extremely fast. There is no plugin ecosystem or drag-and-drop builder — you build exactly what the business needs, nothing more.",
      "Performance — Next.js wins clearly. A well-built Next.js site consistently outscores WordPress on Google's Core Web Vitals, which directly affect where you rank in search results. WordPress, especially when loaded with plugins and running on cheap shared hosting, can be painfully slow without significant optimization work.",
      "Security — Next.js wins again. WordPress is the most hacked CMS on the internet, largely because of outdated plugins and themes maintained by third parties. A Next.js application has a dramatically smaller attack surface, and when deployed on Vercel or similar platforms, security is handled at the infrastructure level.",
      "Ease of content management — WordPress wins. A non-technical business owner can manage their own WordPress site with no developer help. With Next.js, content updates typically require a developer — unless you pair it with a headless CMS like Sanity or Contentful, which adds cost and complexity.",
      "Our recommendation: choose WordPress if your business is content-heavy, your team wants to self-manage, and budget is the primary constraint. Choose Next.js if you want a fast, secure, future-proof site that performs well on Google and scales with your business. At Jengeame, we build in Next.js for the majority of our client projects — and the performance results consistently speak for themselves.",
    ],
  },
  {
    id: "flutter-vs-react-native-2025",
    title: "Flutter vs React Native in 2025: Which Mobile Framework Should You Choose?",
    excerpt:
      "Flutter or React Native? Both are excellent choices for cross-platform mobile apps — but they serve different needs. Here is an honest, practical comparison to help you decide.",
    category: "Mobile Development",
    date: "2025-04-15",
    author: "Antony Ochieng",
    readTime: "7 min read",
    tags: ["Flutter", "React Native", "Mobile Apps", "Cross-Platform", "App Development Kenya"],
    content: [
      "Choosing between Flutter and React Native is one of the most common decisions for businesses building a mobile app in 2025. Both frameworks let you ship apps for iOS and Android from a single codebase — saving significant time and cost compared to building two separate native apps. But they have real differences that matter depending on your project and team.",
      "Flutter is built by Google and uses the Dart programming language. It compiles directly to native ARM code and ships its own rendering engine, which means every pixel on screen is drawn by Flutter itself — not the operating system. This gives you pixel-perfect consistency across platforms and exceptional animation performance. It is the stronger choice for visually rich, custom-designed apps.",
      "React Native is backed by Meta and uses JavaScript (or TypeScript). It bridges to native UI components, so your app uses the platform's own buttons, navigation, and UI patterns. This can feel more native on each platform, and the JavaScript ecosystem is enormous — there is a library for almost anything. If your team already knows React from web development, the learning curve is far shorter.",
      "Performance-wise, Flutter generally wins for graphics-heavy and animation-intensive apps. React Native has closed the gap significantly with its New Architecture (JSI and Fabric renderer), and for most business apps — dashboards, e-commerce, booking systems — either framework will feel fast and smooth.",
      "Developer availability matters too, especially in Kenya and across Africa. JavaScript and React Native developers are far more common than Dart and Flutter specialists, which can affect hiring timelines and freelance costs. That said, Flutter is growing rapidly and many agencies now specialize in it.",
      "Our honest recommendation: choose Flutter if you need a highly polished custom UI, complex animations, or the most consistent cross-platform experience. Choose React Native if your team is JavaScript-first, you need deep third-party integrations, or you want to share logic with a React web application.",
      "At Jengeame, we primarily build with Flutter because the development speed, UI quality, and performance consistently meet the standard our clients expect. That said, we will always recommend the right tool for your specific project — not simply the one we are most comfortable with.",
    ],
  },
  {
    id: "rest-api-design-best-practices-2025",
    title: "REST API Design: 5 Best Practices Every Developer Must Know in 2025",
    excerpt:
      "Build APIs that are clean, predictable, and easy to consume. These five principles separate amateur backends from production-grade systems that teams actually enjoy working with.",
    category: "Backend",
    date: "2025-04-01",
    author: "Simon Gatungo",
    readTime: "6 min read",
    tags: ["REST API", "Backend Development", "Node.js", "Django", "Best Practices"],
    content: [
      "A well-designed REST API is the backbone of any modern application. Whether you are building a mobile app backend, a web platform, or a public API for third-party developers, these five principles will make your APIs cleaner, more maintainable, and far easier for other developers — and your future self — to work with.",
      "1. Use nouns, not verbs, for endpoints. This is the most commonly broken rule in REST design. Instead of /getUser or /createPost, use /users and /posts. The HTTP method already describes the action: GET retrieves, POST creates, PUT or PATCH updates, and DELETE removes. Consistent noun-based endpoints make your API predictable and intuitive without needing to read documentation first.",
      "2. Version your API from day one. Add a version prefix to all endpoints from the very beginning: /api/v1/users. When you need to introduce breaking changes later, release /api/v2 — existing clients continue working on v1 and can migrate to the new version on their own schedule. Skipping versioning is the single most painful mistake developers make when building APIs that others depend on.",
      "3. Return correct HTTP status codes. Do not return 200 OK for everything and bury errors inside the response body — that forces every client to parse your response before knowing whether the request succeeded. Use meaningful codes: 200 (success), 201 (resource created), 400 (bad request), 401 (unauthorized), 403 (forbidden), 404 (not found), 422 (validation error), 500 (server error). Your API becomes self-documenting.",
      "4. Paginate every list endpoint. Never return an unbounded list of records. Returning 50,000 rows in a single response is a server killer and a terrible developer experience. Use offset pagination (?page=2&limit=20) for simple use cases, or cursor-based pagination for large, frequently-updated datasets. Always include metadata in the response: total_count, has_next_page, and the next cursor or page number.",
      "5. Document everything with OpenAPI or Swagger. Write your API specification in OpenAPI format — it auto-generates interactive documentation, client SDKs, and Postman collections. Tools like FastAPI, Hono, and NestJS can generate OpenAPI specs directly from your code with minimal extra work. Good documentation is what separates an API developers enjoy using from one they dread. At Jengeame, every backend we ship includes full API documentation as a standard deliverable.",
    ],
  },
];
